import React from 'react'
import Navbar from './components/Navbar'
import Head from "next/head";

export default function About() {
  return (
    <div>
    <Head>
      <title>Alejandro{"'"}s Portfolio - About</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar activeLink={"about"} />
    </div>
  )
}
