import React from "react";
import Navbar from "./components/Navbar";
import Head from "next/head";
import NoContent from "./components/NoContent";
import MediumNavbar from "./components/MediumNavbar";
import SmallNavbar from "./components/SmallNavbar";
import Footer from "./components/Footer";

export default function About() {
  return (
    <div>
      <Head>
        <title>Alejandro{"'"}s Portfolio - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar activeLink={"about"} />

      <MediumNavbar />
      <SmallNavbar />
      <main>
        <NoContent />
      </main>
      <Footer />
    </div>
  );
}
