import React from "react";
import Head from "next/head";
import Navbar from "./components/Navbar";
import NoContent from "./components/NoContent";
import MediumNavbar from "./components/MediumNavbar";
import SmallNavbar from "./components/SmallNavbar";
import Footer from "./components/Footer";

export default function Blog() {
  return (
    <div>
      <Head>
        <title>Alejandro{"'"}s Portfolio - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar activeLink={"blog"} />
      <MediumNavbar />
      <SmallNavbar />

      <main>
        <NoContent />
      </main>
      <Footer />
    </div>
  );
}
