import React from 'react'
import Head from "next/head";
import Navbar from './components/Navbar';

export default function Blog() {
  return (
    <div className="">
    <Head>
      <title>Alejandro{"'"}s Portfolio - Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar activeLink={"blog"} />
    </div>
  )
}
