import React from "react";
import Head from "next/head";
import Navbar from "./components/Navbar";
import Projects from "./components/Projects";
import MediumNavbar from "./components/MediumNavbar";
import SmallNavbar from "./components/SmallNavbar";
import Footer from "./components/Footer";

export default function Portfolio() {
  return (
    <div className="">
      <Head>
        <title>Alejandro{"'"}s Portfolio - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar activeLink={"portfolio"} />
      <MediumNavbar />
      <SmallNavbar />
      <main>
        <Projects />
      </main>
      <Footer />
    </div>
  );
}
